# Site settings
title: "victormruiz"
bye_message: "Thx!"
baseurl: "/"
url: "https://gjuniioor.github.io"
disqus: gjuniioor
exclude: [vendor]

# Build settings
markdown: kramdown
permalink: /:categories/:title/
